language: python

python:
  - "3.5"

branches:
  only:
    - feature/feature-4-storm-detection

notifications:
  slack: teambash-iu:Kumv5imwDciZcFQ2KvvUHIje

sudo: false

install: true

before_script:
  - cd core/python/stormDetection
  - pip install Flask

script: nosetests

before_deploy:
  - cd ../../../
  - zip -r TeamBash_stormDetection_test.zip core/python/stormDetection scripts appspec.yml Dockerfile || true
  - mkdir -p "stormDetection"
  - mv TeamBash_stormDetection_test.zip stormDetection/TeamBash_stormDetection_test.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teambash-test
    local_dir: stormDetection
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: feature/feature-4-storm-detection

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teambash-test
    key: TeamBash_stormDetection_test.zip
    bundle_type: zip
    application: TeamBash-Test
    deployment_group: TeamBash-Test
    region: us-west-2
    on:
      branch: feature/feature-4-storm-detection
