language: node_js

node_js:
- "4.5.0"

notifications:
  email:
    -srameshv@indiana.edu

branches:
  only:
    - feature/feature-13-forecast-trigger

sudo: true

before_install:
- cd core/javascript/ForecastTrigger/

install:
- npm install

before_deploy:
  - cd ../../../
  - zip -r ForecastTrigger.zip core/javascript/ForecastTrigger scripts appspec.yml || true
  - mkdir -p "teambash"
  - mv ForecastTrigger.zip teambash/ForecastTrigger.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY	
    bucket: sga-teambash
    local_dir: teambash
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: feature/feature-13-forecast-trigger

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teambash
    key: ForecastTrigger.zip
    bundle_type: zip
    application: TeamBash-App
    deployment_group: TeamBash-App
    region: us-west-2
    on:
      branch: feature/feature-13-forecast-trigger
