language: python

python:
  - "2.7"

branches:
  only:
    - feature/feature-3-data-ingestor

notifications:
  email:
    - srameshv@indiana.edu

sudo: false

install: true

script: nosetests

before_deploy:
  - cd ..
  - zip -r TeamBash_DataIngestor.zip core/python/DataIngestor scripts appspec.yml || true
  - mkdir -p "dataIngestor_upload"
  - mv TeamBash_DataIngestor.zip dataIngestor_upload/TeamBash_DataIngestor.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teambash
    local_dir: dataIngestor_upload
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: airavata-courses/TeamBash 
      branch: feature/feature-3-data-ingestor
 
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teambash
    key: TeamBash_DataIngestor.zip
    bundle_type: zip
    application: TeamBash-App
    deployment_group: TeamBash-App
    region: us-west-2
    on:
      repo: airavata-courses/TeamBash
      branch: feature/feature-3-data-ingestor

