language: python

python:
  - "2.7"

branches:
  only:
    - feature/feature-3-data-ingestor

install: true

notifications:
  slack: teambash-iu:Kumv5imwDciZcFQ2KvvUHIje

sudo: false

install: true

before_script:
 - cd core/python/DataIngestor
 - pip install Flask

script: nosetests

before_deploy:
  - cd ../../../
  - zip -r TeamBash_DataIngestor_test.zip core/python/DataIngestor scripts appspec.yml Dockerfile || true
  - mkdir -p "dataIngestor_upload"
  - mv TeamBash_DataIngestor_test.zip dataIngestor_upload/TeamBash_DataIngestor_test.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teambash-test
    local_dir: dataIngestor_upload
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: airavata-courses/TeamBash 
      branch: feature/feature-3-data-ingestor
 
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teambash-test
    key: TeamBash_DataIngestor_test.zip
    bundle_type: zip
    application: TeamBash-Test
    deployment_group: TeamBash-Test
    region: us-west-2
    on:
      repo: airavata-courses/TeamBash
      branch: feature/feature-3-data-ingestor

